[Unit]
Wants=app-dev.lizardbyte.app.Sunshine.service parra.service hypridle.service vicinae.service
Before=app-dev.lizardbyte.app.Sunshine.service parra.service hypridle.service vicinae.service

[Service]
ExecStartPre=-%h/.local/scripts/graphical-session-env enter ${XDG_SESSION_ID} %h/.config/envs/common.env %h/.config/envs/prime.env
ExecStopPost=-%h/.local/scripts/graphical-session-env leave ${XDG_SESSION_ID}
