protocal file
ext log
action launch --title ${FILE} --type=os-window tail -f ${FILE_PATH}

protocal file
fragment_matches [0-9]+
action launch --type=overlay nvim +$FRAGMENT $FILE_PATH

protocal file
mime text/*
action launch --type=overlay nvim $FILE_PATH

protocal file
mime image/*
action launch --type=overlay kitty +kitten icat --hold $FILE_PATH

protocal filelist
action send_text all ${FRAGMENT}
