#!/bin/bash

path=$(dirname "$(readlink -f "$0")")
. "$path"/../../utils/apply-color-helper

file="$path"/../fish/post.d/fetch.fish

sed -i -E "s/(set -g fetch_color\s+\"#)([0-9a-fA-F]{6})(\")/\1${colorHex}\3/" "$file" || {
    log_error "Failed to edit ${file}"
    exit 1
}

log_success "fastfetch"