#!/bin/bash

path=$(dirname "$(readlink -f "$0")")
[ -f "$HOME/.local/snippets/apply-color-helper" ] || {
    echo "Missing helper script: $HOME/.local/snippets/apply-color-helper"
    exit 1
}
. "$HOME/.local/snippets/apply-color-helper"

file="$path"/config.rasi

if pgrep -x "rofi" -u "$USER" >/dev/null; then
    pkill -x rofi || log_error "Failed to kill rofi process"
    # and move on
fi

sed -i -E "s/^(\s*primary:\s*#)([0-9A-Fa-f]{6})(;)/\1${colorHex}\3/" "$file" || {
    log_error "Failed to edit ${file}"
    exit 1
}

log_success "rofi"

