#!/bin/sh

path=$(dirname "$(readlink -f "$0")")
. "$path"/../.utils/apply-color-parse-arg

file="$path"/style.css

sed -i -E "s/^(@define-color\s+flavor\s+#)([0-9A-Fa-f]{6})(;)/\1${colorHex}\3/" "$file" || {
    log_error "Failed to edit ${file}"
    exit 1
}

if pgrep -x "waybar" -u "$USER" > /dev/null; then
    waybar-toggle restart || log_error "Failed to restart waybar"
fi

log_success "waybar"