#!/bin/sh

path=$(dirname "$(readlink -f "$0")")
. "$path"/../.utils/apply-color-parse-arg

if pgrep -x "quickshell" -u "$USER" >/dev/null; then
    qs ipc call colors setPrimary ${colorHex} || {
        log_error "Failed to send IPC command to quickshell"
        exit 1
    }

    log_success "quickshell"
else
    log_error "quickshell is not running. Cannot apply color."
    exit 1
fi