$lock_cmd = pidof hyprlock || hyprlock
$lock_cmd = /home/kolkas/.local/scripts/lock-now
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = $lock_cmd
}

listener {
    timeout = 180 # 3mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300 # 5mins
    on-timeout = hyprctl dispatch dpms off || niri msg action power-off-monitors
    on-resume = hyprctl dispatch dpms on || niri msg action power-on-monitors
}

#listener {
#    timeout = 540 # 9mins
#    on-timeout = $suspend_cmd
#}
