#!/usr/bin/env python3

# Description:
#   A screenshot utility script for Hyprland and Niri desktop environments.
#   Takes screenshots (full, area, window) and provides an option to edit them immediately
#
# Requirements:
# - hyprshot (for Hyprland)
# - - (niri has screenshot functionality built-in)
# - gradia (for editing)
# - glib bindings for python

import argparse
import subprocess
import time
from os import environ
from datetime import datetime
from enum import Enum
from pathlib import Path
from shutil import copy2

# autopep8: off
import gi

gi.require_version("Notify", "0.7")
from gi.repository import Notify, GLib
# autopep8: on


class ScreenshotType(Enum):
    FULL = "full"
    AREA = "area"
    WINDOW = "window"


SCREENSHOT_DIR = Path.home() / "Pictures" / "Screenshots"


def wait_until_file_exists(filepath: Path, timeout: int = 5):
    """Wait until a file exists or timeout."""
    start_time = time.time()
    while not filepath.exists():
        if time.time() - start_time > timeout:
            return False
        time.sleep(0.05)
    return True


def take_screenshot(filepath: Path, typeStr: str):
    type = ScreenshotType(typeStr)
    currentDesktop = environ.get("XDG_CURRENT_DESKTOP", "")
    if "Hyprland" in currentDesktop:
        cmd = {
            ScreenshotType.FULL: f"hyprshot -z -m output -m active -o {SCREENSHOT_DIR} -f ",  # since I only have one monitor
            ScreenshotType.AREA: f"hyprshot -z -m region -o {SCREENSHOT_DIR} -f ",
            ScreenshotType.WINDOW: f"hyprshot -z -m window -o {SCREENSHOT_DIR} -f ",
        }
        process = subprocess.run(f"{cmd[type]}{filepath.name}", shell=True)
        if process.returncode != 0:
            raise RuntimeError("Failed to take screenshot: hyprshot command failed.")
        wait_until_file_exists(filepath)
    elif "niri" in currentDesktop:
        cmd = {
            ScreenshotType.FULL: "niri msg action screenshot-screen",
            ScreenshotType.AREA: "niri msg action screenshot",
            ScreenshotType.WINDOW: "niri msg action screenshot-window",
        }
        niriScreenshotPath = SCREENSHOT_DIR / ".niri_screenshot.png"
        if niriScreenshotPath.exists():
            niriScreenshotPath.unlink()
        # if os.system(cmd[type]):
        process = subprocess.run(cmd[type], shell=True)
        if process.returncode != 0:
            raise RuntimeError("Failed to take screenshot: niri built-in screenshot command failed.")
        wait_until_file_exists(niriScreenshotPath)
        if niriScreenshotPath.exists():
            # niriScreenshotPath.rename(filepath)
            copy2(niriScreenshotPath, filepath)
        else:
            raise RuntimeError("Failed to take screenshot: screenshot file nto found after niri command.")
        wait_until_file_exists(filepath)
    else:
        # print("Unsupported desktop environment.")
        raise RuntimeError("Unsupported desktop environment.")


def edit_screenshot(filepath: Path):
    subprocess.run(f"gradia {filepath}", shell=True)
    # subprocess.run(f"spectacle -l --edit-existing {filepath}", shell=True)


def gen_file_name(prefix="screenshot", ext=".png"):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    return f"{prefix}_{timestamp}{ext}"


if __name__ == "__main__":
    Notify.init("Screenshot Utility")

    try:
        # raise RuntimeError("Never gonna give you up, never gonna let you down.")
        parser = argparse.ArgumentParser(description="Take screenshots with hyprshot.")
        parser.add_argument(
            "type",
            choices=[t.value for t in ScreenshotType],
            help="Type of screenshot to take.",
        )
        args = parser.parse_args()

        # file path
        SCREENSHOT_DIR.mkdir(parents=True, exist_ok=True)
        filename = gen_file_name()
        filepath = SCREENSHOT_DIR / filename

        # take screenshot
        take_screenshot(filepath, args.type)

        # check if successful
        if not filepath.exists():
            raise RuntimeError("Failed to take screenshot: screenshot file not found.")

        # create loop instance
        loop = GLib.MainLoop()
        editing = False

        # callback on default action (edit)
        def edit_callback(n, action, user_data):
            try:
                global editing
                editing = True
                edit_screenshot(filepath)
            finally:
                n.close()
                loop.quit()

        # callback on close
        def close_callback(n):
            global editing
            if not editing:
                loop.quit()

        n = Notify.Notification.new(
            "Screenshot Taken",
            # Mako doesn't have action buttons displayed with notification cards,
            "Click to edit",
        )
        n.add_action(
            # so default action is used, which will be triggered on simply clicking the notification card
            "default",
            # But for my (or more accurate, Noctalia's) quickshell config, buttons will be displayed with label, even for the default action
            "Open in Editor",
            edit_callback,
            None,
        )

        # set timeout for close_callback
        GLib.timeout_add_seconds(10, close_callback, n)

        n.show()
        loop.run()
    except Exception as e:
        n = Notify.Notification.new(
            "Screenshot Error",
            str(e),
        )
        n.show()
