#!/usr/bin/env bash

# Description:
#   Unmount all cifs mounts
#
# Requirements:
# - cifs-utils
# - ./issu
# - sudo privileges

path=$(dirname "$(realpath "$0")")

"$path"/issu && {
    echo "Do not run this script in sudo mode."
    exit 1
}

mount_points=$(mount | grep ' type cifs ' | awk '{print $3}')

[ -z "$mount_points" ] && {
    echo "No cifs mounts found."
    exit 0
}

for mp in $mount_points; do
    echo "Unmounting $mp"
    sudo umount "$mp" || {
        echo "Failed to unmount $mp"
        exit 1
    }
done