#!/usr/bin/env bash

# Description:
#   Quick snippet to reload and restart Waydroid.
#
# Requirements:
# - waydroid
# - sudo privileges

set -e

waydroid session stop
# sudo waydroid upgrade # since I'm not using the default image
sudo waydroid init -f
sudo systemctl restart waydroid-container
waydroid show-full-ui