#!/usr/bin/env bash

# Description:
#   Restart xdg-desktop-portal and xdg-desktop-portal-hyprland to fix screen sharing issues.
#   From hyprland documentation.

sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland -v &
sleep 2
/usr/lib/xdg-desktop-portal &
