[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["ruff", "pyright"]

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "json"
auto-format = false
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "yaml"
auto-format = false
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[language-server.ruff]
command = "ruff"
args = ["server"]
