[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["ruff"]

[language-server.ruff]
command = "ruff"
args = ["server"]
