#!/bin/bash

path=$(dirname "$(readlink -f "$0")")
. "$path"/../../utils/apply-color-helper

file="$HOME/.local/share/nwg-look/gsettings"

sed -i -E "s/^(gtk-theme=catppuccin-mocha-)[^-]+(-standard\+default)$/\1${colorName}\2/" "$file" || {
    log_error "Failed to edit ${file}"
    exit 1
}

nwg-look -a -x

log_success "nwg-look"