#!/bin/bash

path=$(dirname "$(readlink -f "$0")")
. "$path"/../../utils/apply-color-helper

kvantummanager --set catppuccin-mocha-"$colorName" || {
    log_error "Failed to set kvantum theme to catppuccin-mocha-${colorName}"
    exit 1
}

log_success "kvantum"