# MONITOR CONFIG
monitor=,preferred,auto,1

# monitor=eDP-1,2560x1600@240,auto,1.25,bitdepth,10
monitor=eDP-2,2560x1600@240,auto,1.25,bitdepth,10

monitorv2 {
    output = eDP-1
    mode = 2560x1600@240
    scale = 1.25
    bitdepth = 10

    # comment out following lines to disabled HDR
    supports_wide_color = true
    supports_hdr = true
    cm = hdr
    sdrbrightness = 1.4
}
