#!/bin/sh

path=$(dirname "$(readlink -f "$0")")
. "$path"/../.utils/apply-color-parse-arg

file="$path"/post.d/fetch.fish

sed -i 's/^\(    set -g fetch_color "\)#\([0-9a-fA-F]\{6\}\)"/\1#'"${colorHex}"'"/' "$file" || {
    log_error "Failed to edit ${file}"
    exit 1
}

log_success "fastfetch"

# Also apply to omp in here

file="$path"/../posh_theme.omp.json

sed -i 's/\("foreground":[[:space:]]*"\)#\([0-9a-fA-F]\{6\}\)"/\1#'"${colorHex}"'"/g' "$file" || {
    log_error "Failed to edit ${file}"
    exit 1
}

log_success "oh-my-posh"