#!/bin/bash

path=$(dirname "$(readlink -f "$0")")
. "$path"/../../utils/apply-color-helper

file="$path"/config
entry="border-color"

sed -i -E "0,/^($entry\s*=\s*#)([0-9A-Fa-f]{6})/s//\1${colorHex}/" "$file" || {
    log_error "Failed to edit ${file} for entry ${entry}"
    exit 1
}

if pgrep -x "mako" -u "$USER" > /dev/null; then
    makoctl reload || {
        log_error "Failed to reload mako"
        exit 1
    }
fi

log_success "mako"